replicaCount: 2

image:
  repository: anastasiya315510/world_of_games
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


mysql:
  host: world-of-games-db
  secretName: world-of-games-db-secret
  persistentVolume:
    size: 1Gi